<a href="https://colab.research.google.com/github/joseperu2503/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Crear matriz

In [2]:
A = np.array([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


# Crear matriz de Ceros

In [ ]:
Z = np.zeros((3,2))
print(Z)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Crear matriz Identidad

In [ ]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Transpuesta de una matriz

In [4]:
A_transpuesta1 = np.transpose(A)  #forma 1
print(A_transpuesta1)
A_transpuesta2 = A.T              #forma 2
print(A_transpuesta2)

[[1 3]
 [2 4]
 [3 5]]
[[1 3]
 [2 4]
 [3 5]]


# Inversa de una matriz


In [ ]:
B = np.array([[1,0,1],[0,1,1],[-1,1,1]])
print(B)
inversa_B = np.linalg.inv(B)
print(inversa_B)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]
[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


# Pseudoinversa de una matriz

In [ ]:
C = np.array([[2, 3], [5, 7], [11, 13]])
print(C)
C_pse = np.linalg.pinv(C)
print(C_pse)

[[ 2  3]
 [ 5  7]
 [11 13]]
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
